#prebared by Ibrahim Salman (learn in depth)
CC=arm-none-eabi-
CFLAGS=-mcpu=arm926ej-s  -g
INCS=-I
LIBS=
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o) # same as OBJS = $(patsubst %.c,%.o,$SRC)
As = $(wildcard *.s)
AsOBJ = $(As:.s=.o)
Project_name = learn-in-depth

all: $(Project_name).bin
    @echo "-----Build is done-----"

%.o: %.s
    $(CC)as.exe  $(CFLAGS) $< -o $@ 2> log
	
%.o: %.c
    $(CC)gcc.exe  $(CFLAGS) $(INCS) -c $< -o $@

$(Project_name).elf: $(OBJ) $(AsOBJ)
	$(CC)ld.exe  -T linker_script.ld  $(LIBS)  $(OBJ) $(AsOBJ)  -o $@ -Map=Map_file.map
	
$(Project_name).bin: $(Project_name).elf	
    $(CC)objcopy.exe  -O binary $<  $@
	
clean all:
    rm *.o *.elf *.bin
   @echo "Everything Clean"
clean:
	rm *elf *.bin
	@echo "Everything Clean"