/*
 * STEPPER_Config.h
 *
 *  Created on: Mar 21, 2024
 *      Author: Admin
 */

#ifndef HAL_STEPPER_STEPPER_CONFIG_H_
#define HAL_STEPPER_STEPPER_CONFIG_H_

#define STEPPER_PORT		DIO_PORTA

#define STEPPER_BLUE_PIN 	DIO_PIN0
#define STEPPER_PINK_PIN 	DIO_PIN1
#define STEPPER_YELLOW_PIN 	DIO_PIN2
#define STEPPER_ORANGE_PIN 	DIO_PIN3

#endif /* HAL_STEPPER_STEPPER_CONFIG_H_ */
